config/routes.rb
Nutrientmanager::Application.routes.draw do
  resources :allergies


  resources :mealrecipes


  resources :mealplans


  resources :meals


  resources :nutritionists


  resources :clients


  resources :recipes


  resources :userprofiles


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    elsif user.has_role? :nutr
      can :manage, Recipe
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/allergy.rb
class Allergy < ActiveRecord::Base
  attr_accessible :description, :name
  has_many  :clientallergies
  has_many  :clients, :through => :clientallergies
end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to  :user
  belongs_to  :nutritionist
  has_many  :clientallergies
  has_many  :allergies, :through => :clientallergies
end

app/models/clientallergy.rb
class Clientallergy < ActiveRecord::Base
  attr_accessible :allergy_id, :client_id
  belongs_to  :client
  belongs_to  :allergy
end

app/models/meal.rb
class Meal < ActiveRecord::Base
  attr_accessible :amount, :mealofday
  has_many  :mealrecipes
  has_many  :recipes, :through => :mealrecipes
end

app/models/mealplan.rb
class Mealplan < ActiveRecord::Base
  attr_accessible :client_id, :meal_id
end

app/models/mealrecipe.rb
class Mealrecipe < ActiveRecord::Base
  attr_accessible :meal_id, :recipe_id
end

app/models/nutritionist.rb
class Nutritionist < ActiveRecord::Base
  attr_accessible :something
  belongs_to  :user, :dependent => :destroy
  has_many  :clients, :dependent => :destroy
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :name
  has_many  :mealrecipes
  has_many  :meals, :through => :mealrecipes
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :userprofile_attributes

  has_one :userprofile
  accepts_nested_attributes_for :userprofile, :allow_destroy => true

end

app/models/userprofile.rb
class Userprofile < ActiveRecord::Base
  attr_accessible :address, :city, :firstname, :gender, :lastname, :phone, :user_id, :zipcode

  belongs_to :user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/nutritionists_controller.rb
class NutritionistsController < ApplicationController
  # GET /nutritionists
  # GET /nutritionists.json
  def index
    @nutritionists = Nutritionist.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @nutritionists }
    end
  end

  # GET /nutritionists/1
  # GET /nutritionists/1.json
  def show
    @nutritionist = Nutritionist.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @nutritionist }
    end
  end

  # GET /nutritionists/new
  # GET /nutritionists/new.json
  def new
    @nutritionist = Nutritionist.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @nutritionist }
    end
  end

  # GET /nutritionists/1/edit
  def edit
    @nutritionist = Nutritionist.find(params[:id])
  end

  # POST /nutritionists
  # POST /nutritionists.json
  def create
    @nutritionist = Nutritionist.new(params[:nutritionist])

    respond_to do |format|
      if @nutritionist.save
        format.html { redirect_to @nutritionist, notice: 'Nutritionist was successfully created.' }
        format.json { render json: @nutritionist, status: :created, location: @nutritionist }
      else
        format.html { render action: "new" }
        format.json { render json: @nutritionist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /nutritionists/1
  # PUT /nutritionists/1.json
  def update
    @nutritionist = Nutritionist.find(params[:id])

    respond_to do |format|
      if @nutritionist.update_attributes(params[:nutritionist])
        format.html { redirect_to @nutritionist, notice: 'Nutritionist was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @nutritionist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nutritionists/1
  # DELETE /nutritionists/1.json
  def destroy
    @nutritionist = Nutritionist.find(params[:id])
    @nutritionist.destroy

    respond_to do |format|
      format.html { redirect_to nutritionists_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/allergies_helper.rb
module AllergiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mealplans_helper.rb
module MealplansHelper
end

app/helpers/mealrecipes_helper.rb
module MealrecipesHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/nutritionists_helper.rb
module NutritionistsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/nutritionists/_form.html.erb
<%= simple_form_for(@nutritionist) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :something %>
    <%= f.input :user_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/nutritionists/edit.html.erb
<h1>Editing nutritionist</h1>

<%= render 'form' %>

<%= link_to 'Show', @nutritionist %> |
<%= link_to 'Back', nutritionists_path %>

app/views/nutritionists/index.html.erb
<h1>Listing nutritionists</h1>

<table>
  <tr>
    <th>Something</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @nutritionists.each do |nutritionist| %>
  <tr>
    <td><%= nutritionist.something %></td>
    <td><%= nutritionist.user_id %></td>
    <td><%= link_to 'Show', nutritionist %></td>
    <td><%= link_to 'Edit', edit_nutritionist_path(nutritionist) %></td>
    <td><%= link_to 'Destroy', nutritionist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>


<br />

<%= link_to 'New Nutritionist', new_nutritionist_path %>

app/views/nutritionists/new.html.erb
<h1>New nutritionist</h1>

<%= render 'form' %>

<%= link_to 'Back', nutritionists_path %>

app/views/nutritionists/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Something:</b>
  <%= @nutritionist.something %>
</p>

<p>
  <b>User:</b>
  <%= @nutritionist.user_id %>
</p>

<br />
<p><b>List of clients</b></p>
<table class="table table-striped table-bordered table-hover table-condensed">
  <tr>
    <th>Name</th>
    <th>Preference</th>
    <th>Allergy</th>
  </tr>
  <% @nutritionist.clients do |c| %>
    <tr>
      <td><%= c.user.name %></td>
      <td><%= c.preference %></td>
      <td><%= c.allergy %></td>
    </tr>
  <% end %>
</table>

<%= link_to 'Edit', edit_nutritionist_path(@nutritionist) %> |
<%= link_to 'Back', nutritionists_path %>