config/routes.rb
Nutrientmanager::Application.routes.draw do
  resources :allergies


  resources :mealrecipes


  resources :mealplans


  resources :meals


  resources :nutritionists


  resources :clients


  resources :recipes


  resources :userprofiles


  authenticated :user do
    root :to => 'home#index'
  end
  root :to => "home#index"
  devise_for :users
  resources :users
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role? :admin
      can :manage, :all
    elsif user.has_role? :nutr
      can :manage, Recipe
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user permission to do.
    # If you pass :manage it will apply to every action. Other common actions here are
    # :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on. If you pass
    # :all it will apply to every resource. Otherwise pass a Ruby class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details: https://github.com/ryanb/cancan/wiki/Defining-Abilities
  end
end

app/models/allergy.rb
class Allergy < ActiveRecord::Base
  attr_accessible :description, :name
  has_many  :clientallergies
  has_many  :clients, :through => :clientallergies
end

app/models/client.rb
class Client < ActiveRecord::Base
  belongs_to  :user
  belongs_to  :nutritionist
  has_many  :clientallergies
  has_many  :allergies, :through => :clientallergies
end

app/models/clientallergy.rb
class Clientallergy < ActiveRecord::Base
  attr_accessible :allergy_id, :client_id
  belongs_to  :client
  belongs_to  :allergy
end

app/models/meal.rb
class Meal < ActiveRecord::Base
  attr_accessible :amount, :mealofday
  has_many  :mealrecipes
  has_many  :recipes, :through => :mealrecipes
end

app/models/mealplan.rb
class Mealplan < ActiveRecord::Base
  attr_accessible :client_id, :meal_id
end

app/models/mealrecipe.rb
class Mealrecipe < ActiveRecord::Base
  attr_accessible :meal_id, :recipe_id
end

app/models/nutritionist.rb
class Nutritionist < ActiveRecord::Base
  attr_accessible :something
  belongs_to  :user, :dependent => :destroy
  has_many  :clients, :dependent => :destroy
end

app/models/recipe.rb
class Recipe < ActiveRecord::Base
  attr_accessible :name
  has_many  :mealrecipes
  has_many  :meals, :through => :mealrecipes
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :role_ids, :as => :admin
  attr_accessible :name, :email, :password, :password_confirmation, :remember_me, :userprofile_attributes

  has_one :userprofile
  accepts_nested_attributes_for :userprofile, :allow_destroy => true

end

app/models/userprofile.rb
class Userprofile < ActiveRecord::Base
  attr_accessible :address, :city, :firstname, :gender, :lastname, :phone, :user_id, :zipcode

  belongs_to :user
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/userprofiles_controller.rb
class UserprofilesController < ApplicationController
  # GET /userprofiles
  # GET /userprofiles.json
  def index
    @userprofiles = Userprofile.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @userprofiles }
    end
  end

  # GET /userprofiles/1
  # GET /userprofiles/1.json
  def show
    @userprofile = Userprofile.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @userprofile }
    end
  end

  # GET /userprofiles/new
  # GET /userprofiles/new.json
  def new
    @userprofile = Userprofile.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @userprofile }
    end
  end

  # GET /userprofiles/1/edit
  def edit
    @userprofile = Userprofile.find(params[:id])
  end

  # POST /userprofiles
  # POST /userprofiles.json
  def create
    @userprofile = Userprofile.new(params[:userprofile])

    respond_to do |format|
      if @userprofile.save
        format.html { redirect_to @userprofile, notice: 'Userprofile was successfully created.' }
        format.json { render json: @userprofile, status: :created, location: @userprofile }
      else
        format.html { render action: "new" }
        format.json { render json: @userprofile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /userprofiles/1
  # PUT /userprofiles/1.json
  def update
    @userprofile = Userprofile.find(params[:id])

    respond_to do |format|
      if @userprofile.update_attributes(params[:userprofile])
        format.html { redirect_to @userprofile, notice: 'Userprofile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @userprofile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /userprofiles/1
  # DELETE /userprofiles/1.json
  def destroy
    @userprofile = Userprofile.find(params[:id])
    @userprofile.destroy

    respond_to do |format|
      format.html { redirect_to userprofiles_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/allergies_helper.rb
module AllergiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper

  def display_base_errors resource
    return '' if (resource.errors.empty?) or (resource.errors[:base].empty?)
    messages = resource.errors[:base].map { |msg| content_tag(:p, msg) }.join
    html = <<-HTML
    <div class="alert alert-error alert-block">
      <button type="button" class="close" data-dismiss="alert">&#215;</button>
      #{messages}
    </div>
    HTML
    html.html_safe
  end

end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mealplans_helper.rb
module MealplansHelper
end

app/helpers/mealrecipes_helper.rb
module MealrecipesHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/userprofiles_helper.rb
module UserprofilesHelper
end

app/views/userprofiles/_form.html.erb
<%= simple_form_for(@userprofile) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :firstname %>
    <%= f.input :lastname %>
    <%= f.input :gender %>
    <%= f.input :address %>
    <%= f.input :city %>
    <%= f.input :zipcode %>
    <%= f.input :phone %>
    <%= f.input :user_id %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/userprofiles/edit.html.erb
<h1>Editing userprofile</h1>

<%= render 'form' %>

<%= link_to 'Show', @userprofile %> |
<%= link_to 'Back', userprofiles_path %>

app/views/userprofiles/index.html.erb
<h1>Listing userprofiles</h1>

<table>
  <tr>
    <th>Firstname</th>
    <th>Lastname</th>
    <th>Gender</th>
    <th>Address</th>
    <th>City</th>
    <th>Zipcode</th>
    <th>Phone</th>
    <th>User</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @userprofiles.each do |userprofile| %>
  <tr>
    <td><%= userprofile.firstname %></td>
    <td><%= userprofile.lastname %></td>
    <td><%= userprofile.gender %></td>
    <td><%= userprofile.address %></td>
    <td><%= userprofile.city %></td>
    <td><%= userprofile.zipcode %></td>
    <td><%= userprofile.phone %></td>
    <td><%= userprofile.user_id %></td>
    <td><%= link_to 'Show', userprofile %></td>
    <td><%= link_to 'Edit', edit_userprofile_path(userprofile) %></td>
    <td><%= link_to 'Destroy', userprofile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Userprofile', new_userprofile_path %>

app/views/userprofiles/new.html.erb
<h1>New userprofile</h1>

<%= render 'form' %>

<%= link_to 'Back', userprofiles_path %>

app/views/userprofiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Firstname:</b>
  <%= @userprofile.firstname %>
</p>

<p>
  <b>Lastname:</b>
  <%= @userprofile.lastname %>
</p>

<p>
  <b>Gender:</b>
  <%= @userprofile.gender %>
</p>

<p>
  <b>Address:</b>
  <%= @userprofile.address %>
</p>

<p>
  <b>City:</b>
  <%= @userprofile.city %>
</p>

<p>
  <b>Zipcode:</b>
  <%= @userprofile.zipcode %>
</p>

<p>
  <b>Phone:</b>
  <%= @userprofile.phone %>
</p>

<p>
  <b>User:</b>
  <%= @userprofile.user_id %>
</p>


<%= link_to 'Edit', edit_userprofile_path(@userprofile) %> |
<%= link_to 'Back', userprofiles_path %>